### ISSUE TITLE
Using Material-Icons

### ISSUE THREAD

**Issue by alexcvaz** [jpilfold/ngx-image-viewer#19]
I need to use the class material-icons, the way it works today is not possible, I used the fork and made the necessary changes, I wonder if you are interested in releasing this version. Or how can I proceed?
Thank you.

**Comment by jpilfold** [comment]
@alexcvaz 
Hi, thanks for your interest.

I won't be merging your fork because it would introduce breaking changes. I have also managed to use material-icons without making any changes to the library.

I've created a StackBlitz to demo with the next / prev buttons coming from material icons.

https://stackblitz.com/edit/angular-cqrxb4?file=styles.css

I'd be happy to talk through the steps involved if you like
